"""Regenerate book/_static/py/embeddings.py and book/_static/data/ch03-retrieval.json.

    python3 scripts/embed_handbook.py            # embed with Azure, then write the widget data
    python3 scripts/embed_handbook.py --no-embed # only rewrite the widget data (retrieval.py changed)

Run it whenever handbook.py or retrieval.SCRIPTED_QUESTIONS changes. It reads the Foundry key
from the signed-in Azure CLI at run time; the key is never written anywhere.
"""
import json
import math
import os
import subprocess
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PY = os.path.join(ROOT, "book", "_static", "py")
OUT_PY = os.path.join(PY, "embeddings.py")
OUT_JSON = os.path.join(ROOT, "book", "_static", "data", "ch03-retrieval.json")
ACCOUNT, GROUP = "dl-foundry-msba-workshop", "DL_ResourceGroup_01"
URL = f"https://{ACCOUNT}.cognitiveservices.azure.com/openai/v1/embeddings"
DIM = 256
sys.path.insert(0, PY)


def _key():
    return subprocess.check_output(["az", "cognitiveservices", "account", "keys", "list", "-g", GROUP, "-n", ACCOUNT,
                                    "--query", "key1", "-o", "tsv"], text=True).strip()


def _embed(texts, key):
    out = []
    for i in range(0, len(texts), 64):
        body = json.dumps({"model": "text-embedding-3-small", "input": texts[i:i + 64], "dimensions": DIM}).encode()
        req = urllib.request.Request(URL, body, {"Content-Type": "application/json", "Authorization": f"Bearer {key}"})
        with urllib.request.urlopen(req, timeout=60) as r:
            out += [d["embedding"] for d in sorted(json.load(r)["data"], key=lambda d: d["index"])]
    return out


def _pca2(vecs):
    """Two principal axes by power iteration, so the map widget can draw 256 numbers as a dot."""
    n, d = len(vecs), len(vecs[0])
    mean = [sum(v[j] for v in vecs) / n for j in range(d)]
    X = [[v[j] - mean[j] for j in range(d)] for v in vecs]
    axes = []
    for _ in range(2):
        a = [1.0 / math.sqrt(d)] * d
        for _ in range(200):
            proj = [sum(x[j] * a[j] for j in range(d)) for x in X]
            a = [sum(proj[i] * X[i][j] for i in range(n)) for j in range(d)]
            for b in axes:  # stay orthogonal to the first axis
                dot = sum(a[j] * b[j] for j in range(d))
                a = [a[j] - dot * b[j] for j in range(d)]
            s = math.sqrt(sum(t * t for t in a))
            a = [t / s for t in a]
        axes.append(a)
    return mean, axes


def _write_py(chunk_vecs, q_vecs, map2d):
    r4 = lambda v: [round(x, 4) for x in v]
    with open(OUT_PY, "w") as f:
        f.write('"""Generated by scripts/embed_handbook.py - do not edit. text-embedding-3-small, 256 dimensions."""\n')
        f.write(f"DIM = {DIM}\n")
        f.write("CHUNK_VECS = {\n" + "".join(f"    {k!r}: {r4(v)},\n" for k, v in chunk_vecs.items()) + "}\n")
        f.write("QUESTION_VECS = {\n" + "".join(f"    {k!r}: {r4(v)},\n" for k, v in q_vecs.items()) + "}\n")
        f.write("MAP_2D = {\n" + "".join(f"    {k!r}: {[round(x, 3) for x in v]},\n" for k, v in map2d.items()) + "}\n")


def main():
    if not os.path.exists(OUT_PY):
        open(OUT_PY, "w").write("DIM = 256\nCHUNK_VECS = {}\nQUESTION_VECS = {}\nMAP_2D = {}\n")
    if "--no-embed" not in sys.argv:
        from handbook import CLAUSES
        import retrieval
        key = _key()
        cv = dict(zip([c["id"] for c in CLAUSES], _embed([c["text"] for c in CLAUSES], key)))
        qs = sorted({retrieval.norm(q) for q in retrieval.SCRIPTED_QUESTIONS})
        qv = dict(zip(qs, _embed(qs, key)))
        mean, axes = _pca2(list(cv.values()))
        place = lambda v: [sum((v[j] - mean[j]) * a[j] for j in range(DIM)) for a in axes]
        m2 = {k: place(v) for k, v in cv.items()}
        m2.update({f"q:{k}": place(v) for k, v in qv.items()})
        _write_py(cv, qv, m2)
        print(f"embedded {len(cv)} clauses and {len(qv)} questions")
        for mod in ("retrieval", "embeddings"):
            sys.modules.pop(mod, None)
    import retrieval
    from embeddings import MAP_2D
    data = {"chunks": [{"id": c["id"], "heading": c["heading"], "text": c["text"]} for c in retrieval.CHUNKS],
            "map": MAP_2D,
            "presets": [{**p, "results": {m: [{"id": r["id"], "score": r["score"]} for r in retrieval.search(p["q"], m, 5)]
                                          for m in retrieval.METHODS}} for p in retrieval.PRESETS]}
    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
    with open(OUT_JSON, "w") as f:
        json.dump(data, f, indent=1)
    print(f"wrote {os.path.relpath(OUT_JSON, ROOT)} ({len(data['presets'])} presets); embeddings.py {os.path.getsize(OUT_PY) // 1024} KB")


if __name__ == "__main__":
    main()
